language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
- '[ "$TRAVIS_OS_NAME" = linux ] && sudo apt-get update -qq || brew update'
install:
- '[ "$TRAVIS_OS_NAME" = linux ] && sudo apt-get install -y libsdl1.2-dev || brew install sdl'