[package]
name = "rl"
version = "0.1.0"
authors = ["Joe Clay <27cupsofcoffee@gmail.com>"]
edition = "2018"

[dependencies]
tetra = { version = "0.6", default-features = false, features = ["texture_png"] }
hecs = "0.5"
rand = "0.8"

[profile.dev.package."*"]
opt-level = 3
