name: CI Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
    - name: Install native dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libasound2-dev
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Run build via Cargo
      run: cargo build --verbose
